fix for Issue1916  Pgr_point_t.
pgRouting/pgrouting pull request #2030
Opened 2021-07-20 12:00 UTC by ManasviGoyal

Fixes #1926

Changes proposed in this pull request:

-changes to pgr_point_t..h
-adjusting code based on changes on structure Pgr_point_t.

@pgRouting/admins

2021-07-20 12:28 UTC, ManasviGoyal commented
@cvvergara pls check and so sorry for the incorrect references. pls tell if i can fix that

2021-07-20 17:25 UTC, cvvergara requested changes

2021-07-20 17:25 UTC, cvvergara commented on include/c_common/pgr_point_input.h
> +typedef struct Pgr_point_input_t Pgr_point_input_t;
The actions will point if it is wrong (by sight it is), probably you need to change to
```
typedef struct Pgr_point_t Pgr_point_t;
```
btw, maximum 2 commits.
```
git fetch upstream
git rebase -i upstream/develop
```
Use fixup, to put the extra commits into one (help shows on the same file it opens)

2021-07-21 01:16 UTC, cvvergara commented
@ManasviGoyal Now you need to try fixup the commits

2021-07-21 10:54 UTC, ManasviGoyal commented
@cvvergara i tried to fixup but it now added other commits which were made before me. what is it that i am doing wrong?

2021-07-21 11:29 UTC, closed without merging