Issue1929
pgRouting/pgrouting pull request #2038
Opened 2021-07-25 20:49 UTC by abhichou4

Fixes #1929.

Changes proposed in this pull request:
- changes to `trsp.h`
- adjusting code based on changes on structure `edge_t`, `restrict_t`, and `path_element_tt`.

These changes were introduced to fix compilation errors.
-  `struct` keyword was added before respective structs.
- `#include <stdbool.h>` so bool can be used in `trsp.h`
- Moved typedef for `int_64` and `double` outside `#ifdef __cplusplus` condition cause it's needed in `trsp.c` as well.

@pgRouting/admins

2021-07-25 21:01 UTC, abhichou4 commented
The boost-supported version checks seem to be failing on my fork, saying `<stddef.h>` should be included in `trsp.h`. Do let me know if you think it should be included.

2021-07-28 01:55 UTC, cvvergara requested changes

2021-07-28 01:55 UTC, cvvergara commented on include/c_types/trsp/trsp.h
> +typedef int64_t int64;
Please put this back on the `#ifdef __cplusplus`

2021-07-28 01:59 UTC, cvvergara commented
Something is wrong definitively.
as you can see by clicking the "Details" button, its not compiling
https://github.com/pgRouting/pgrouting/pull/2038/checks?check_run_id=3177663396#step:8:78
Maybe try with another one, and then come back to this one

2021-07-28 02:00 UTC, cvvergara commented
I converted to draft, so that you can keep on working on it.
Mark as "Ready for review" when you see that all the tests pass

2021-07-28 02:19 UTC, cvvergara commented
You also need be more explicit on the title of the PR
For example:
https://github.com/pgRouting/pgrouting/pull/2036

2021-07-28 08:40 UTC, abhichou4 commented
> Something is wrong definitively.
> as you can see by clicking the "Details" button, it's not compiling.
> https://github.com/pgRouting/pgrouting/pull/2038/checks?check_run_id=3177663396#step:8:78
> Maybe try with another one, and then come back to this one

Yes, I later noticed it fails to build. It can't seem to find `-lpostgres` while linking.

2021-08-04 17:28 UTC, abhichou4 commented
Opening another new branch to handle extensive merge conflicts.

2021-08-04 17:28 UTC, closed without merging