[ksp][doc] fixing wording
pgRouting/pgrouting pull request #2502
Opened 2023-03-28 11:04 UTC by Aniket-debug

Changes proposed in this pull request:
- fix wording
-
-

@pgRouting/admins

2023-03-28 23:07 UTC, cvvergara commented
I am wondering, why the 2 PR are different.
Didnt you do a cherry-pick?

2023-03-28 23:08 UTC, cvvergara requested changes
The changes are not the same as in #2489

2023-03-29 04:52 UTC, Aniket-debug commented
I added the same commit now.

2023-04-06 19:09 UTC, cvvergara approved these changes

2023-04-06 19:10 UTC, merged